// ============================================================
// 365 PUZZLES DE XADREZ - Talento Dev / Chess Land
// Um puzzle diferente por dia durante 1 ano inteiro!
// Substitua o array PUZZLES no seu index.html por este.
// ============================================================

var PUZZLES = [
  // --- JANEIRO ---
  { fen: '6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',                              solution: ['e1e8'],       theme: 'Mate em 1',           desc: 'Torre dá mate na 8ª fileira!',           hint: 'A torre vai para e8' },
  { fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4', solution: ['f3g5'],      theme: 'Ataque ao Rei',        desc: 'Cavalo ataca o ponto f7!',               hint: 'O cavalo salta para g5' },
  { fen: '4r1k1/pp3ppp/2p5/8/3P4/1P3Q2/P4PPP/5RK1 w - - 0 1',                   solution: ['f3f7'],       theme: 'Sacrifício',           desc: 'Dama invade na 7ª fileira!',             hint: 'A dama vai para f7' },
  { fen: '6k1/pp4pp/2p5/4Pb2/4p3/1P2Q3/P5PP/5RK1 w - - 0 1',                   solution: ['e5f7'],       theme: 'Bispo Decisivo',       desc: 'O bispo ataca o rei!',                   hint: 'Bispo captura em f7' },
  { fen: '8/8/8/8/8/6k1/6p1/6K1 w - - 0 1',                                    solution: ['g1f1'],       theme: 'Final de Reis',        desc: 'Rei branco deve recuar!',                hint: 'O rei vai para f1' },
  { fen: 'r2q1rk1/pp2ppbp/2np1np1/8/3NP3/2N1BP2/PPPQ2PP/R3KB1R w KQ - 0 10',  solution: ['d4f5'],       theme: 'Lance Central',        desc: 'Cavalo salta para posição dominante!',   hint: 'O cavalo vai para f5' },
  { fen: '5rk1/p4ppp/1p6/3pq3/3B4/1P3Q2/P4PPP/5RK1 w - - 0 1',                solution: ['d4g7'],       theme: 'Combinação',           desc: 'O bispo ataca decisivamente!',           hint: 'Bispo vai para g7' },
  { fen: 'r1b1kb1r/pppp1ppp/2n5/4p3/2BNP3/8/PPP2PPP/RNBQK2R b KQkq - 0 1',   solution: ['c6d4'],       theme: 'Garfo de Cavalo',      desc: 'O cavalo faz garfo!',                    hint: 'Cavalo captura em d4' },
  { fen: '2r3k1/p4ppp/1p6/3p4/3B4/1P3P2/P5PP/3R2K1 w - - 0 1',               solution: ['d4h8'],       theme: 'Diagonal Fatal',       desc: 'Bispo domina a diagonal longa!',         hint: 'Bispo vai para h8' },
  { fen: 'r3r1k1/pp3ppp/2pb4/3p4/3P1B2/2N2P2/PPP3PP/R3R1K1 w - - 0 1',       solution: ['f4d6'],       theme: 'Peça Dominante',       desc: 'Bispo captura peça importante!',         hint: 'Bispo captura em d6' },
  { fen: '6k1/5p2/4p1p1/3p4/8/1P3PPP/P7/6K1 w - - 0 1',                       solution: ['g1f2'],       theme: 'Final de Peões',       desc: 'Rei ativa para o final!',                hint: 'Rei vai para f2' },
  { fen: 'r1bqkbnr/ppp2ppp/2np4/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1', solution: ['f3g5'],      theme: 'Abertura Italiana',    desc: 'Ataque ao ponto f7!',                    hint: 'Cavalo salta para g5' },
  { fen: '4k3/8/4K3/4P3/8/8/8/8 w - - 0 1',                                   solution: ['e6d6'],       theme: 'Final K+P',            desc: 'Oposição de reis!',                      hint: 'Rei vai para d6' },
  { fen: 'r2qkb1r/ppp1pppp/2n5/3p1b2/3P1B2/2N2N2/PPP1PPPP/R2QKB1R w KQkq - 0 1', solution: ['f4d6'],  theme: 'Troca Favorável',      desc: 'Troca vantajosa no centro!',             hint: 'Bispo captura em d6' },
  { fen: '3r2k1/pp3ppp/2p5/8/3Q4/8/PPP2PPP/6K1 w - - 0 1',                    solution: ['d4d8'],       theme: 'Dama Dominante',       desc: 'Dama captura torre!',                    hint: 'Dama vai para d8' },
  { fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1', solution: ['c4f7'], theme: 'Ataque Légal',        desc: 'Sacrifício clássico em f7!',             hint: 'Bispo captura em f7' },
  { fen: '6k1/8/6K1/8/8/8/8/4R3 w - - 0 1',                                   solution: ['e1e8'],       theme: 'Torre Básico',         desc: 'Torre dá xeque-mate!',                   hint: 'Torre vai para e8' },
  { fen: 'r1b1k2r/pppp1ppp/2n2n2/2b1p1N1/2B1P3/8/PPPP1PPP/RNBQK2R w KQkq - 0 1', solution: ['g5f7'], theme: 'Sacrifício Cavalo',    desc: 'Cavalo sacrifica em f7!',                hint: 'Cavalo captura em f7' },
  { fen: '4r1k1/5pp1/7p/8/8/8/5PPP/4R1K1 w - - 0 1',                           solution: ['e1e8'],       theme: 'Troca de Torres',      desc: 'Torre captura e força vantagem!',        hint: 'Torre troca em e8' },
  { fen: 'r3k3/8/8/8/8/8/8/R3K3 w Qq - 0 1',                                   solution: ['a1a8'],       theme: 'Torres no Final',      desc: 'Torre domina a coluna aberta!',          hint: 'Torre vai para a8' },
  { fen: '2r3k1/6pp/8/8/8/8/6PP/2R3K1 w - - 0 1',                              solution: ['c1c8'],       theme: 'Coluna Aberta',        desc: 'Torre penetra na 8ª fileira!',           hint: 'Torre vai para c8' },
  { fen: '5rk1/5ppp/8/8/8/8/5PPP/5RK1 w - - 0 1',                              solution: ['f1f8'],       theme: 'Torres Opostas',       desc: 'Torre captura para vencer!',             hint: 'Torre vai para f8' },
  { fen: 'r1bqkb1r/pp3ppp/2np1n2/4p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 0 1', solution: ['c4f7'],   theme: 'Sacrifício Clássico',  desc: 'Bispo sacrifica em f7!',                 hint: 'Bispo captura em f7' },
  { fen: '4k3/4p3/4K3/8/8/8/8/8 b - - 0 1',                                    solution: ['e7e6'],       theme: 'Oposição',             desc: 'Peão avança para defesa!',               hint: 'Peão vai para e6' },
  { fen: '8/8/4k3/4p3/4P3/4K3/8/8 w - - 0 1',                                  solution: ['e3d3'],       theme: 'Final Clássico',       desc: 'Rei manobra para vencer!',               hint: 'Rei vai para d3' },
  { fen: 'r2q1rk1/ppp2ppp/2n1bn2/3pp3/2B1P3/2NP1N2/PPP2PPP/R1BQR1K1 w - - 0 1', solution: ['c4f7'],   theme: 'Ataque ao Rei',        desc: 'Sacrifício abre o rei negro!',           hint: 'Bispo captura em f7' },
  { fen: '6k1/5ppp/8/8/2B5/8/5PPP/6K1 w - - 0 1',                              solution: ['c4f7'],       theme: 'Bispo Longo',          desc: 'Bispo domina a diagonal!',               hint: 'Bispo vai para f7' },
  { fen: 'r1b1kbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPPBPPP/RNBQK2R b KQkq - 0 1',  solution: ['c6d4'],       theme: 'Garfo Central',        desc: 'Cavalo faz garfo no centro!',            hint: 'Cavalo vai para d4' },
  { fen: '2b1kb1r/pppp1ppp/2n5/4p1N1/2B1P3/8/PPPP1PPP/RNBQK2R w KQkq - 0 1', solution: ['g5f7'],       theme: 'Ataque Rápido',        desc: 'Cavalo destrói a posição negra!',        hint: 'Cavalo captura em f7' },
  { fen: '4r1k1/5ppp/8/3p4/3P4/8/5PPP/4R1K1 w - - 0 1',                        solution: ['e1e8'],       theme: 'Coluna e',             desc: 'Torre domina coluna aberta!',            hint: 'Torre vai para e8' },
  { fen: '8/5pk1/8/8/8/8/5PK1/8 w - - 0 1',                                    solution: ['g2g3'],       theme: 'Final P+R',            desc: 'Rei ativa no final!',                    hint: 'Rei avança para g3' },

  // --- FEVEREIRO ---
  { fen: 'r1bq1rk1/ppp2ppp/2nb4/3pp3/4P3/3P1N2/PPP1BPPP/RNBQ1RK1 w - - 0 1', solution: ['f3e5'],       theme: 'Cavalo Central',       desc: 'Cavalo captura peão central!',           hint: 'Cavalo vai para e5' },
  { fen: '3r2k1/p4ppp/1p6/2b5/8/1P4P1/P4P1P/3R2K1 w - - 0 1',                 solution: ['d1d8'],       theme: 'Torres 7ª',            desc: 'Torre invade a 8ª fileira!',             hint: 'Torre vai para d8' },
  { fen: 'r3r1k1/pp1b1ppp/3p4/2pP4/4n3/2N1BN2/PP3PPP/R3R1K1 w - - 0 1',      solution: ['e3c5'],       theme: 'Captura Decisiva',     desc: 'Bispo captura peão passado!',            hint: 'Bispo vai para c5' },
  { fen: '2r2rk1/pp3ppp/2n5/3p4/3P4/2N5/PP3PPP/2R2RK1 w - - 0 1',            solution: ['c1c8'],       theme: 'Penetração',           desc: 'Torre penetra na 8ª!',                   hint: 'Torre vai para c8' },
  { fen: 'r2q1rk1/pp3ppp/2pb4/3p4/3P4/2PB4/PP3PPP/R2Q1RK1 w - - 0 1',        solution: ['d3h7'],       theme: 'Bispo h7',             desc: 'Bispo ataca o rei pelo flanco!',         hint: 'Bispo vai para h7' },
  { fen: '5rk1/pp3ppp/2p5/8/4B3/1P4P1/P4P1P/5RK1 w - - 0 1',                  solution: ['e4d5'],       theme: 'Bispo Ativo',          desc: 'Bispo domina diagonal central!',         hint: 'Bispo vai para d5' },
  { fen: 'r4rk1/pp3ppp/2p5/3p4/3P4/2P5/PP3PPP/R4RK1 w - - 0 1',              solution: ['a1a8'],       theme: 'Coluna a',             desc: 'Torre penetra pela coluna a!',           hint: 'Torre vai para a8' },
  { fen: 'r1b2rk1/pp3ppp/2p5/3p1b2/3P4/2PB4/PP3PPP/R1B2RK1 w - - 0 1',       solution: ['d3f5'],       theme: 'Troca de Bispos',      desc: 'Troca favorável de bispos!',             hint: 'Bispo captura em f5' },
  { fen: '4r1k1/pp1b1ppp/2p5/3p4/3P4/2PB4/PP3PPP/4R1K1 w - - 0 1',           solution: ['d3h7'],       theme: 'Diagonal Fatal',       desc: 'Bispo mira no rei!',                     hint: 'Bispo vai para h7' },
  { fen: '2r3k1/pp3pp1/7p/3p4/3P4/5P1P/PP4P1/2R3K1 w - - 0 1',               solution: ['c1c8'],       theme: 'Coluna c',             desc: 'Torre domina coluna c!',                 hint: 'Torre vai para c8' },
  { fen: 'r3k2r/pp3ppp/2p5/3p4/3P4/2P5/PP3PPP/R3K2R w KQkq - 0 1',           solution: ['a1a8'],       theme: 'Roque e Ataque',       desc: 'Torre penetra antes do roque!',          hint: 'Torre vai para a8' },
  { fen: '6k1/pp3ppp/8/3p4/3P4/8/PP3PPP/6K1 w - - 0 1',                       solution: ['g1f2'],       theme: 'Rei Ativo',            desc: 'Rei centraliza no final!',               hint: 'Rei vai para f2' },
  { fen: 'r1bqr1k1/pp3ppp/2p2n2/3p4/3P4/2PB1N2/PP3PPP/R1BQR1K1 w - - 0 1',  solution: ['d3h7'],       theme: 'Sacrifício h7',        desc: 'Bispo sacrifica em h7!',                 hint: 'Bispo vai para h7' },
  { fen: 'r2q1r1k/pp4pp/2p2p2/3p4/3P4/2PQ4/PP4PP/R4R1K w - - 0 1',           solution: ['d3h7'],       theme: 'Dama h7',              desc: 'Dama ataca o rei!',                      hint: 'Dama vai para h7' },
  { fen: '5rk1/pp4pp/2p2p2/3p4/3P4/2P5/PP4PP/5RK1 w - - 0 1',                solution: ['f1f8'],       theme: 'Torre Final',          desc: 'Torre captura na 8ª!',                   hint: 'Torre vai para f8' },
  { fen: '2r3k1/p5pp/1p3p2/3p4/3P4/1P3P2/P5PP/2R3K1 w - - 0 1',              solution: ['c1c8'],       theme: 'Invasão',              desc: 'Torre invade a posição negra!',          hint: 'Torre vai para c8' },
  { fen: 'r1b1r1k1/pp3ppp/2p2n2/3p4/3P4/2P2N2/PP3PPP/R1B1R1K1 w - - 0 1',   solution: ['f3e5'],       theme: 'Outpost',              desc: 'Cavalo ocupa casa forte!',               hint: 'Cavalo vai para e5' },
  { fen: '4r1k1/pp3ppp/2p2n2/3p4/3P4/2P5/PP3PPP/4R1K1 w - - 0 1',            solution: ['e1e8'],       theme: 'Torre Ativa',          desc: 'Torre captura na 8ª!',                   hint: 'Torre vai para e8' },
  { fen: 'r3r1k1/pp3ppp/8/3p4/3P4/8/PP3PPP/R3R1K1 w - - 0 1',                solution: ['e1e8'],       theme: 'Torres Dobradas',      desc: 'Torres cooperam!',                       hint: 'Torre vai para e8' },
  { fen: '6k1/5ppp/8/3p4/3P4/8/5PPP/6K1 w - - 0 1',                           solution: ['g1f2'],       theme: 'Final Peões',          desc: 'Rei ativa para o final!',                hint: 'Rei vai para f2' },
  { fen: 'r2q1rk1/pp3ppp/2p2n2/3p4/3P4/2PQ1N2/PP3PPP/R4RK1 w - - 0 1',      solution: ['d3h7'],       theme: 'Mate Clássico',        desc: 'Sacrifício leva ao mate!',               hint: 'Dama vai para h7' },
  { fen: '4rrk1/pp3ppp/2p5/3p4/3P4/2P5/PP3PPP/4RRK1 w - - 0 1',              solution: ['e1e8'],       theme: 'Torres na 8ª',         desc: 'Torres dobram na 8ª fileira!',           hint: 'Torre vai para e8' },
  { fen: 'r4rk1/pp3ppp/2p2n2/3p4/3P4/2P2N2/PP3PPP/R4RK1 w - - 0 1',          solution: ['f3e5'],       theme: 'Cavalo Forte',         desc: 'Cavalo ocupa central forte!',            hint: 'Cavalo vai para e5' },
  { fen: '2r2rk1/pp3ppp/2p5/3p4/3P1B2/2P5/PP3PPP/2R2RK1 w - - 0 1',          solution: ['f4d6'],       theme: 'Bispo d6',             desc: 'Bispo domina casa d6!',                  hint: 'Bispo vai para d6' },
  { fen: '5rk1/pp2bppp/2p5/3p4/3P4/2P1B3/PP3PPP/5RK1 w - - 0 1',             solution: ['e3d4'],       theme: 'Troca Central',        desc: 'Bispo captura peão central!',            hint: 'Bispo captura em d4... não, vai para d4' },
  { fen: 'r1b2rk1/pp3ppp/2p2n2/3p4/3P4/2P2N2/PP3PPP/R1B2RK1 w - - 0 1',     solution: ['f3e5'],       theme: 'Ponto e5',             desc: 'Cavalo conquista ponto e5!',             hint: 'Cavalo vai para e5' },
  { fen: '4r1k1/pp2bppp/2p5/3p4/3P4/2P5/PP2BPPP/4R1K1 w - - 0 1',            solution: ['e2d3'],       theme: 'Bispo Ativo',          desc: 'Bispo melhora posição!',                 hint: 'Bispo vai para d3' },
  { fen: 'r3r1k1/pp2bppp/2p5/3p4/3P4/2PB4/PP3PPP/R3R1K1 w - - 0 1',          solution: ['d3h7'],       theme: 'Bispo h7+',            desc: 'Bispo dá xeque em h7!',                 hint: 'Bispo vai para h7' },
  { fen: '2r3k1/pp2bppp/2p5/3p4/3P4/2PB4/PP3PPP/2R3K1 w - - 0 1',            solution: ['d3h7'],       theme: 'Ataque ao Flanco',     desc: 'Bispo ataca pelo flanco!',               hint: 'Bispo vai para h7' },

  // --- MARÇO ---
  { fen: 'r1bq1rk1/pp3ppp/2p2n2/3p2B1/3P4/2P2N2/PP3PPP/R2Q1RK1 w - - 0 1',  solution: ['g5f6'],       theme: 'Troca por Cavalo',     desc: 'Bispo captura cavalo!',                  hint: 'Bispo captura em f6' },
  { fen: '6k1/pp2rppp/2p5/3p4/3P4/2P5/PP2RPPP/6K1 w - - 0 1',                solution: ['e2e8'],       theme: 'Torre 8ª',             desc: 'Torre penetra na 8ª!',                   hint: 'Torre vai para e8' },
  { fen: '2r1r1k1/pp3ppp/2p5/3p4/3P4/2P5/PP3PPP/2R1R1K1 w - - 0 1',          solution: ['e1e8'],       theme: 'Torres Coordenadas',   desc: 'Torres trabalham juntas!',               hint: 'Torre vai para e8' },
  { fen: 'r2q1rk1/pp3ppp/2pbn3/3p4/3P4/2PBN3/PP3PPP/R2Q1RK1 w - - 0 1',     solution: ['d3h7'],       theme: 'Bispo h7+',            desc: 'Sacrifício de bispo clássico!',          hint: 'Bispo vai para h7' },
  { fen: '4r1k1/pp3ppp/2p1n3/3p4/3P4/2P1N3/PP3PPP/4R1K1 w - - 0 1',          solution: ['e3f5'],       theme: 'Salto de Cavalo',      desc: 'Cavalo salta para f5!',                  hint: 'Cavalo vai para f5' },
  { fen: 'r3r1k1/pp3ppp/2p1n3/3p4/3P4/2P1N3/PP3PPP/R3R1K1 w - - 0 1',       solution: ['e3f5'],       theme: 'Cavalo f5',            desc: 'Cavalo ocupa f5 forte!',                 hint: 'Cavalo vai para f5' },
  { fen: '5rk1/pp3pp1/2p4p/3p4/3P4/2P4P/PP3PP1/5RK1 w - - 0 1',              solution: ['f1f8'],       theme: 'Torre Invade',         desc: 'Torre captura na 8ª!',                   hint: 'Torre vai para f8' },
  { fen: '2r3k1/pp3pp1/2p4p/3p4/3P4/2P4P/PP3PP1/2R3K1 w - - 0 1',            solution: ['c1c8'],       theme: 'Coluna c Aberta',      desc: 'Torre explora coluna c!',                hint: 'Torre vai para c8' },
  { fen: '4r1k1/pp3pp1/2p4p/3p4/3P4/2P1B2P/PP3PP1/4R1K1 w - - 0 1',          solution: ['e3h6'],       theme: 'Bispo h6',             desc: 'Bispo ameaça o rei!',                    hint: 'Bispo vai para h6' },
  { fen: 'r4rk1/pp3pp1/2p4p/3p4/3P1B2/2P4P/PP3PP1/R4RK1 w - - 0 1',          solution: ['f4d6'],       theme: 'Bispo d6',             desc: 'Bispo domina casa d6!',                  hint: 'Bispo vai para d6' },
  { fen: 'r1bqr1k1/pp3ppp/2p5/3p2n1/3P2B1/2P2N2/PP3PPP/R1BQR1K1 w - - 0 1', solution: ['g4d7'],       theme: 'Captura Decisiva',     desc: 'Bispo captura peça importante!',         hint: 'Bispo vai para d7' },
  { fen: '4r1k1/ppb2ppp/2p5/3p4/3P4/2PB4/PP3PPP/4R1K1 w - - 0 1',            solution: ['d3h7'],       theme: 'Bispo Fatal',          desc: 'Bispo dá xeque-mate!',                   hint: 'Bispo vai para h7' },
  { fen: 'r2q1rk1/ppp2ppp/2n2n2/3pp3/1bB1P3/2NP1N2/PPP2PPP/R1BQ1RK1 w - - 0 1', solution: ['c4f7'],  theme: 'Sacrifício f7',        desc: 'Sacrifício clássico em f7!',             hint: 'Bispo captura em f7' },
  { fen: '6k1/ppp2ppp/8/3p4/3P4/8/PPP2PPP/6K1 w - - 0 1',                    solution: ['g1f2'],       theme: 'Final Simples',        desc: 'Rei entra no jogo!',                     hint: 'Rei vai para f2' },
  { fen: 'r1b1r1k1/ppp2ppp/2n2n2/3pp3/2B1P3/2NP1N2/PPP2PPP/R1B1R1K1 w - - 0 1', solution: ['c4f7'],  theme: 'Bispo f7',             desc: 'Sacrifício decisivo em f7!',             hint: 'Bispo captura em f7' },
  { fen: '2r1r1k1/ppp2ppp/5n2/3pp3/2B1P3/2NP1N2/PPP2PPP/2R1R1K1 w - - 0 1', solution: ['c4f7'],       theme: 'Combinação f7',        desc: 'Ataque em f7 ganha material!',           hint: 'Bispo captura em f7' },
  { fen: 'r1bqkb1r/ppp2ppp/2n5/3pp1N1/2B1P3/8/PPPP1PPP/RNBQK2R w KQkq - 0 1', solution: ['g5f7'],    theme: 'Cavalo f7',            desc: 'Cavalo destrói posição negra!',          hint: 'Cavalo captura em f7' },
  { fen: 'r1b2rk1/ppp2ppp/2n5/3pp3/2BNP3/3P4/PPP2PPP/R1B2RK1 w - - 0 1',    solution: ['d4f5'],       theme: 'Cavalo Forte',         desc: 'Cavalo ocupa f5!',                       hint: 'Cavalo vai para f5' },
  { fen: '4r1k1/ppp2ppp/2n5/3p4/3P4/2N5/PPP2PPP/4R1K1 w - - 0 1',            solution: ['e1e8'],       theme: 'Torre Rápida',         desc: 'Torre penetra na 8ª!',                   hint: 'Torre vai para e8' },
  { fen: 'r2q1rk1/ppp1bppp/2n5/3pp3/4P3/2NP1N2/PPP1BPPP/R2Q1RK1 w - - 0 1', solution: ['f3g5'],       theme: 'Cavalo g5',            desc: 'Cavalo ataca o ponto f7!',               hint: 'Cavalo vai para g5' },
  { fen: '3r2k1/ppp2ppp/2n5/3pp3/4P3/2NP4/PPP2PPP/3R2K1 w - - 0 1',          solution: ['d1d8'],       theme: 'Torre d8',             desc: 'Torre captura na 8ª!',                   hint: 'Torre vai para d8' },
  { fen: '5rk1/ppp2ppp/2n5/3p4/3P4/2N5/PPP2PPP/5RK1 w - - 0 1',              solution: ['f1f8'],       theme: 'Torre f8',             desc: 'Torre invade pelo flanco!',              hint: 'Torre vai para f8' },
  { fen: 'r4rk1/ppp2ppp/2n5/3p4/3P4/2N5/PPP2PPP/R4RK1 w - - 0 1',            solution: ['a1a8'],       theme: 'Torre a8',             desc: 'Torre penetra pela coluna a!',           hint: 'Torre vai para a8' },
  { fen: '2r2rk1/ppp2ppp/2n5/3p4/3P4/2N5/PPP2PPP/2R2RK1 w - - 0 1',          solution: ['c1c8'],       theme: 'Torre c8',             desc: 'Torre captura em c8!',                   hint: 'Torre vai para c8' },
  { fen: 'r3r1k1/ppp2ppp/2n5/3p4/3P4/2N5/PPP2PPP/R3R1K1 w - - 0 1',          solution: ['e1e8'],       theme: 'Troca Vantajosa',      desc: 'Torres cooperam para ganhar!',           hint: 'Torre vai para e8' },
  { fen: 'r1b2rk1/ppp1bppp/2n5/3pp3/4P3/2NP1N2/PPP1BPPP/R1B2RK1 w - - 0 1', solution: ['f3e5'],       theme: 'Ponto e5',             desc: 'Cavalo conquista e5!',                   hint: 'Cavalo vai para e5' },
  { fen: '4r1k1/ppp1bppp/2n5/3p4/3P4/2N1B3/PPP1BPPP/4R1K1 w - - 0 1',        solution: ['e3h6'],       theme: 'Bispo Agressor',       desc: 'Bispo ataca posição do rei!',            hint: 'Bispo vai para h6' },
  { fen: '2r1r1k1/ppp1bppp/2n5/3p4/3P4/2N1B3/PPP1BPPP/2R1R1K1 w - - 0 1',   solution: ['e3h6'],       theme: 'Ataque h6',            desc: 'Bispo ataca pelo flanco!',               hint: 'Bispo vai para h6' },
  { fen: 'r2q1rk1/ppp1bppp/2nb4/3p4/3P4/2NBB3/PPP2PPP/R2Q1RK1 w - - 0 1',   solution: ['d3h7'],       theme: 'Sacrifício h7',        desc: 'Bispo sacrifica em h7!',                 hint: 'Bispo vai para h7' },
  { fen: '6k1/ppp1bppp/2n5/3p4/3P4/2N1B3/PPP2PPP/6K1 w - - 0 1',             solution: ['e3h6'],       theme: 'Bispo h6 Livre',       desc: 'Bispo ameaça o rei!',                    hint: 'Bispo vai para h6' },
  { fen: '5rk1/ppp1bppp/2n5/3p4/3P4/2N1B3/PPP2PPP/5RK1 w - - 0 1',           solution: ['e3h6'],       theme: 'Pressão no Flanco',    desc: 'Bispo pressiona pelo flanco!',           hint: 'Bispo vai para h6' },

  // --- ABRIL ---
  { fen: 'r1bq1rk1/ppp2ppp/2n2n2/3p4/3P1B2/2N2N2/PPP2PPP/R2Q1RK1 w - - 0 1', solution: ['f4h6'],      theme: 'Bispo h6',             desc: 'Bispo ataca o rei!',                     hint: 'Bispo vai para h6' },
  { fen: 'r2q1rk1/ppp2ppp/2n5/3p2b1/3P2B1/2N5/PPP2PPP/R2Q1RK1 w - - 0 1',   solution: ['g4d7'],       theme: 'Captura de Bispo',     desc: 'Bispo captura bispo adversário!',        hint: 'Bispo captura em d7' },
  { fen: '2r2rk1/ppp2ppp/2n5/3p2b1/3P2B1/2N5/PPP2PPP/2R2RK1 w - - 0 1',     solution: ['g4d7'],       theme: 'Troca Favorável',      desc: 'Captura favorável de bispo!',            hint: 'Bispo captura em d7' },
  { fen: 'r4rk1/ppp2ppp/2n5/3p2b1/3P2B1/2N5/PPP2PPP/R4RK1 w - - 0 1',       solution: ['g4d7'],       theme: 'Bispo Ativo',          desc: 'Bispo captura peça importante!',         hint: 'Bispo captura em d7' },
  { fen: '4r1k1/ppp2ppp/2n5/3p2b1/3P2N1/2P5/PP3PPP/4R1K1 w - - 0 1',        solution: ['g4f6'],       theme: 'Cavalo f6',            desc: 'Cavalo captura bispo!',                  hint: 'Cavalo vai para f6' },
  { fen: 'r1b2rk1/ppp2ppp/2n5/3p1qn1/3P2B1/2N1BN2/PPP2PPP/R2Q1RK1 w - - 0 1', solution: ['g4d7'],    theme: 'Troca de Damas',       desc: 'Bispo elimina bispo adversário!',        hint: 'Bispo captura em d7' },
  { fen: '6k1/ppp3pp/5p2/3p4/3P4/5P2/PPP3PP/6K1 w - - 0 1',                  solution: ['g1f2'],       theme: 'Rei Centraliza',       desc: 'Rei entra ativamente!',                  hint: 'Rei vai para f2' },
  { fen: 'r3r1k1/ppp3pp/5p2/3p4/3P4/5P2/PPP3PP/R3R1K1 w - - 0 1',           solution: ['e1e8'],       theme: 'Final de Torres',      desc: 'Torre captura na 8ª!',                   hint: 'Torre vai para e8' },
  { fen: '2r1r1k1/ppp3pp/5p2/3p4/3P4/5P2/PPP3PP/2R1R1K1 w - - 0 1',         solution: ['e1e8'],       theme: 'Torres Cooperam',      desc: 'Torres trabalham juntas!',               hint: 'Torre vai para e8' },
  { fen: 'r2q1rk1/ppp3pp/5p2/3p4/3P4/5P2/PPP1QPPP/R4RK1 w - - 0 1',         solution: ['e2e8'],       theme: 'Dama Penetra',         desc: 'Dama invade na 8ª!',                     hint: 'Dama vai para e8' },
  { fen: '5rk1/ppp3pp/5p2/3p4/3P4/5P2/PPP1R1PP/6K1 w - - 0 1',               solution: ['e2e8'],       theme: 'Torre Ataca',          desc: 'Torre captura peça importante!',         hint: 'Torre vai para e8' },
  { fen: 'r1b1r1k1/ppp3pp/5p2/3p4/3P4/2PB1P2/PP4PP/R1B1R1K1 w - - 0 1',     solution: ['d3h7'],       theme: 'Sacrifício Bispo',     desc: 'Bispo sacrifica em h7!',                 hint: 'Bispo vai para h7' },
  { fen: '4r1k1/ppp1qppp/2nb4/3p4/3P4/2NB4/PPP1QPPP/4R1K1 w - - 0 1',       solution: ['d3h7'],       theme: 'Combinação Clássica',  desc: 'Sacrifício de bispo decisivo!',          hint: 'Bispo vai para h7' },
  { fen: '2r1r1k1/ppp1qppp/2nb4/3p4/3P4/2NB4/PPP1QPPP/2R1R1K1 w - - 0 1',   solution: ['d3h7'],       theme: 'Bispo Sacrificado',    desc: 'Bispo abre a posição do rei!',           hint: 'Bispo vai para h7' },
  { fen: 'r2qr1k1/ppp1bppp/2n5/3pp3/4P3/2NP1N2/PPPQBPPP/R3R1K1 w - - 0 1', solution: ['f3g5'],       theme: 'Cavalo Agressivo',     desc: 'Cavalo ataca o ponto f7!',               hint: 'Cavalo vai para g5' },
  { fen: 'r1b1r1k1/ppp1bppp/2n5/3pp3/4P3/2NP1N2/PPP1BPPP/R1B1R1K1 w - - 0 1', solution: ['f3e5'],    theme: 'Ponto e5 Forte',       desc: 'Cavalo domina e5!',                      hint: 'Cavalo vai para e5' },
  { fen: 'r3r1k1/ppp1bppp/2n5/3p4/3P4/2N1B3/PPP1BPPP/R3R1K1 w - - 0 1',     solution: ['e3h6'],       theme: 'Dois Bispos',          desc: 'Bispos trabalham em harmonia!',          hint: 'Bispo vai para h6' },
  { fen: '6k1/ppp1bppp/2n5/3p4/3P4/2N1B3/PPP1BPPP/6K1 w - - 0 1',            solution: ['e2d3'],       theme: 'Melhora de Bispo',     desc: 'Bispo melhora posição!',                 hint: 'Bispo vai para d3' },
  { fen: 'r4rk1/ppp1bppp/2n5/3p4/3P4/2N1B3/PPP1BPPP/R4RK1 w - - 0 1',       solution: ['e3h6'],       theme: 'Bispo Agressor',       desc: 'Bispo ataca o rei!',                     hint: 'Bispo vai para h6' },
  { fen: '2r2rk1/ppp1bppp/2n5/3p4/3P4/2N1B3/PPP1BPPP/2R2RK1 w - - 0 1',     solution: ['e3h6'],       theme: 'Pressão Constante',    desc: 'Bispo aumenta a pressão!',               hint: 'Bispo vai para h6' },
  { fen: 'r1bq1rk1/ppp1bppp/2np1n2/4p3/2B1P3/2NP1N2/PPP1BPPP/R1BQ1RK1 w - - 0 1', solution: ['c4f7'], theme: 'Greco Attack',        desc: 'Sacrifício greco em f7!',                hint: 'Bispo captura em f7' },
  { fen: '5rk1/ppp1bppp/2np1n2/4p3/2B1P3/2NP1N2/PPP1BPPP/5RK1 w - - 0 1',   solution: ['c4f7'],       theme: 'Ataque Grego',         desc: 'Bispo sacrifica em f7!',                 hint: 'Bispo captura em f7' },
  { fen: '4r1k1/ppp1bppp/2np1n2/4p3/2B1P3/2NP1N2/PPP1BPPP/4R1K1 w - - 0 1', solution: ['c4f7'],       theme: 'Combinação f7',        desc: 'Sacrifício em f7 ganha material!',       hint: 'Bispo captura em f7' },
  { fen: 'r4rk1/ppp1bppp/2np1n2/4p3/2B1P3/2NP1N2/PPP1BPPP/R4RK1 w - - 0 1', solution: ['c4f7'],       theme: 'Bispo x f7',           desc: 'Sacrifício clássico!',                   hint: 'Bispo captura em f7' },
  { fen: '2r1r1k1/ppp1bppp/2np1n2/4p3/2B1P3/2NP1N2/PPP1BPPP/2R1R1K1 w - - 0 1', solution: ['c4f7'],  theme: 'Ataque em f7',         desc: 'Bispo abre o rei negro!',                hint: 'Bispo captura em f7' },
  { fen: '6k1/pp3ppp/2p2n2/3p4/3P4/2P2N2/PP3PPP/6K1 w - - 0 1',              solution: ['f3e5'],       theme: 'Cavalo Central',       desc: 'Cavalo conquista e5!',                   hint: 'Cavalo vai para e5' },
  { fen: 'r1b1r1k1/pp3ppp/2p2n2/3p4/3P4/2P2N2/PP3PPP/R1B1R1K1 w - - 0 1',   solution: ['f3e5'],       theme: 'Outpost e5',           desc: 'Cavalo ocupa outpost!',                  hint: 'Cavalo vai para e5' },
  { fen: '2r1r1k1/pp3ppp/2p2n2/3p4/3P4/2P2N2/PP3PPP/2R1R1K1 w - - 0 1',     solution: ['f3e5'],       theme: 'Cavalo Forte',         desc: 'Cavalo conquista ponto forte!',          hint: 'Cavalo vai para e5' },
  { fen: 'r4rk1/pp3ppp/2p2n2/3p4/3P4/2P2N2/PP3PPP/R4RK1 w - - 0 1',          solution: ['f3e5'],       theme: 'Cavalo e5',            desc: 'Cavalo ocupa centro!',                   hint: 'Cavalo vai para e5' },
  { fen: '4r1k1/pp3ppp/2p2n2/3p4/3P1B2/2P2N2/PP3PPP/4R1K1 w - - 0 1',        solution: ['f4h6'],       theme: 'Bispo h6 Fatal',       desc: 'Bispo ameaça mate!',                     hint: 'Bispo vai para h6' },

  // --- MAIO ---
  { fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R b KQkq - 0 1', solution: ['e5d4'],      theme: 'Defesa Escandinava',   desc: 'Peão captura no centro!',                hint: 'Peão captura em d4' },
  { fen: 'r1bqk2r/pppp1ppp/2n2n2/4p3/1bB1P3/2N2N2/PPPP1PPP/R1BQ1RK1 w kq - 0 1', solution: ['c3d5'],  theme: 'Ataque Central',       desc: 'Cavalo expulsa o bispo!',                hint: 'Cavalo vai para d5' },
  { fen: 'r1bqkb1r/pp3ppp/2n5/3pp3/4P3/3P1N2/PPP2PPP/RNBQKB1R w KQkq - 0 1', solution: ['d3d4'],      theme: 'Abertura de Centro',   desc: 'Peão abre o centro!',                    hint: 'Peão vai para d4' },
  { fen: 'r1bq1rk1/pppp1ppp/2n2n2/4p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQ - 0 1', solution: ['c4f7'],    theme: 'Italiana Agressiva',   desc: 'Sacrifício clássico!',                   hint: 'Bispo captura em f7' },
  { fen: 'r1bqk2r/pppp1ppp/2nb1n2/4p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 0 1', solution: ['c4d5'],  theme: 'Troca Central',        desc: 'Bispo toma o centro!',                   hint: 'Bispo vai para d5' },
  { fen: 'rnbqk2r/pppp1ppp/5n2/4p3/2B1P3/8/PPPP1PPP/RNBQK2R w KQkq - 0 1',  solution: ['c4f7'],       theme: 'Mate do Pastor Mod.',  desc: 'Sacrifício decisivo!',                   hint: 'Bispo captura em f7' },
  { fen: 'r1b1k2r/ppppqppp/2n5/4p3/2B1P3/2N5/PPPP1PPP/R1BQK2R w KQkq - 0 1', solution: ['c4f7'],      theme: 'Gambito Evans',        desc: 'Sacrifício agressivo!',                  hint: 'Bispo captura em f7' },
  { fen: 'r1bqkbnr/pp3ppp/2np4/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1', solution: ['c4f7'],      theme: 'Defesa Siciliana',     desc: 'Bispo sacrifica em f7!',                 hint: 'Bispo captura em f7' },
  { fen: 'r1bqk2r/pppp1Bpp/2n2n2/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R b kq - 0 1', solution: ['d8f6'],    theme: 'Xeque Forçado',        desc: 'Dama deve recapturar!',                  hint: 'Dama vai para f6' },
  { fen: 'r2qkb1r/ppp1pppp/2n5/3p4/3P4/2N5/PPP1PPPP/R1BQKB1R w KQkq - 0 1', solution: ['c1g5'],       theme: 'Pressão no Centro',    desc: 'Bispo aumenta pressão!',                 hint: 'Bispo vai para g5' },
  { fen: 'r1bqkb1r/ppp1pppp/2n5/3p4/3PP3/2N5/PPP2PPP/R1BQKB1R b KQkq - 0 1', solution: ['e7e5'],      theme: 'Abertura de Jogo',     desc: 'Peão abre o jogo!',                      hint: 'Peão vai para e5' },
  { fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/2P5/5NP1/PP1PPP1P/RNBQKB1R b KQkq - 0 1', solution: ['d7d5'],     theme: 'Contraataque Centro',  desc: 'Peão ataca o centro!',                   hint: 'Peão vai para d5' },
  { fen: 'rnb1kb1r/pppp1ppp/4p3/8/3Pn3/5N2/PPP1PPPP/RNBQKB1R w KQkq - 0 1', solution: ['d4d5'],       theme: 'Peão Avança',          desc: 'Peão avança no centro!',                 hint: 'Peão vai para d5' },
  { fen: 'r1bqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 0 1', solution: ['b8c6'],         theme: 'Desenvolvimento',      desc: 'Cavalo desenvolve!',                     hint: 'Cavalo vai para c6' },
  { fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1', solution: ['f1b5'],      theme: 'Espanhola Clássica',   desc: 'Bispo joga abertura espanhola!',         hint: 'Bispo vai para b5' },
  { fen: 'r2qkb1r/ppp1pppp/2n2n2/3p4/3P4/2N2N2/PPP1PPPP/R1BQKB1R w KQkq - 0 1', solution: ['c1g5'],   theme: 'Pin no Cavalo',        desc: 'Bispo prende o cavalo!',                 hint: 'Bispo vai para g5' },
  { fen: 'r1b1kb1r/pppp1ppp/2n1pn2/8/3PP3/2N5/PPP2PPP/R1BQKBNR w KQkq - 0 1', solution: ['d4d5'],      theme: 'Avanço Central',       desc: 'Peão avança para ganhar espaço!',        hint: 'Peão vai para d5' },
  { fen: 'r1bqkb1r/pp1ppppp/2n2n2/2p5/3PP3/2N5/PPP2PPP/R1BQKBNR w KQkq - 0 1', solution: ['d4d5'],    theme: 'Siciliana Avanço',     desc: 'Peão avança agresivamente!',             hint: 'Peão vai para d5' },
  { fen: 'r1bqk2r/pppp1ppp/2n2n2/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R b kq - 0 1', solution: ['f8c5'],    theme: 'Italiana Clássica',    desc: 'Bispo ativa na diagonal!',               hint: 'Bispo vai para c5' },
  { fen: 'r2qkbnr/ppp1pppp/2n5/3p4/3P4/2N2N2/PPP1PPPP/R1BQKB1R b KQkq - 0 1', solution: ['c8f5'],     theme: 'Bispo Ativo',          desc: 'Bispo desenvolve ativamente!',           hint: 'Bispo vai para f5' },
  { fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4PP2/8/PPPP2PP/RNBQKBNR b KQkq - 0 1', solution: ['e5f4'],          theme: 'Gambito do Rei',       desc: 'Peão aceita o gambito!',                 hint: 'Peão captura em f4' },
  { fen: 'r1bqkb1r/ppp2ppp/2np1n2/4p3/2B1PP2/2N2N2/PPPP2PP/R1BQK2R b KQkq - 0 1', solution: ['e5f4'], theme: 'Gambito Aceito',        desc: 'Captura do gambito!',                    hint: 'Peão captura em f4' },
  { fen: 'r1b1kbnr/ppppqppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1', solution: ['b1c3'],     theme: 'Desenvolvimento',      desc: 'Cavalo desenvolve!',                     hint: 'Cavalo vai para c3' },
  { fen: 'rnbqkb1r/pppp1ppp/4pn2/8/3PP3/8/PPP2PPP/RNBQKBNR w KQkq - 0 1',  solution: ['d4d5'],          theme: 'Francesa Avanço',      desc: 'Peão avança no centro!',                 hint: 'Peão vai para d5' },
  { fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/3PP3/2N5/PPP2PPP/R1BQKBNR b KQkq - 0 1', solution: ['e5d4'],      theme: 'Captura Central',      desc: 'Peão captura no centro!',                hint: 'Peão captura em d4' },
  { fen: 'r2qkb1r/pp1bpppp/2np1n2/8/2B1P3/2N2N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['c4d5'],    theme: 'Bispo d5',             desc: 'Bispo domina o centro!',                 hint: 'Bispo vai para d5' },
  { fen: 'r1bqkb1r/pp1ppppp/2n2n2/2p5/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1', solution: ['c4f7'],  theme: 'Fried Liver',          desc: 'Sacrifício do Fígado Frito!',            hint: 'Bispo captura em f7' },
  { fen: 'r1bqk2r/ppp2ppp/2np1n2/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1', solution: ['c4d5'], theme: 'Troca de Bispos',       desc: 'Bispo toma ponto central!',              hint: 'Bispo vai para d5' },
  { fen: 'r1bqkb1r/pppp1ppp/2n5/8/2BNP3/8/PPP2PPP/RNBQK2R b KQkq - 0 1',   solution: ['c6d4'],          theme: 'Garfo Duplo',          desc: 'Cavalo faz garfo duplo!',                hint: 'Cavalo vai para d4' },
  { fen: 'r1bq1rk1/pppp1ppp/2n5/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQ1RK1 b - - 0 1', solution: ['f8e7'],     theme: 'Defesa Sólida',        desc: 'Bispo desenvolve defendendo!',           hint: 'Bispo vai para e7' },
  { fen: 'r1bqkbnr/ppp2ppp/2np4/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1', solution: ['c4f7'],     theme: 'Ataque Agressivo',     desc: 'Sacrifício em f7!',                      hint: 'Bispo captura em f7' },

  // --- JUNHO ---
  { fen: 'r1bqk2r/pppp1ppp/2n2n2/4p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R b kq - 0 1', solution: ['f8b4'],   theme: 'Espanhola Dois C.',    desc: 'Bispo prende o cavalo!',                 hint: 'Bispo vai para b4' },
  { fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p1B1/2B1P3/2N5/PPPP1PPP/R2QK1NR b KQkq - 0 1', solution: ['h7h6'], theme: 'Expulsa o Bispo',     desc: 'Peão expulsa o bispo!',                  hint: 'Peão vai para h6' },
  { fen: 'r1bqkb1r/pp1p1ppp/2n2n2/2p1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1', solution: ['c4d5'], theme: 'Ponto d5',          desc: 'Bispo domina ponto central!',            hint: 'Bispo vai para d5' },
  { fen: 'r2qkb1r/pppb1ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['c4d5'], theme: 'Centro Forte',         desc: 'Bispo toma ponto forte!',                hint: 'Bispo vai para d5' },
  { fen: 'r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1', solution: ['c4f7'],  theme: 'Sacrifício Bispo',     desc: 'Bispo sacrifica em f7!',                 hint: 'Bispo captura em f7' },
  { fen: 'r1bqkbnr/pppp1ppp/2n5/4p1N1/4P3/8/PPPP1PPP/RNBQKB1R b KQkq - 0 1', solution: ['d8g5'],      theme: 'Defesa ao Cavalo',     desc: 'Dama ataca o cavalo!',                   hint: 'Dama vai para g5' },
  { fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/3P1N2/PPP2PPP/RNBQKB1R b KQkq - 0 1', solution: ['f8c5'],    theme: 'Bispo Ativo',          desc: 'Bispo desenvolve atacando!',             hint: 'Bispo vai para c5' },
  { fen: 'r1bqk1nr/pppp1ppp/2n5/2b1p3/1PB1P3/5N2/P1PP1PPP/RNBQK2R b KQkq - 0 1', solution: ['c5b4'], theme: 'Gambito Aceito',        desc: 'Bispo captura o gambito!',               hint: 'Bispo captura em b4' },
  { fen: 'r1bqkb1r/ppp2ppp/2n2n2/3pp3/4P3/3P1N2/PPP2PPP/RNBQKB1R w KQkq - 0 1', solution: ['e4d5'],  theme: 'Peão Captura',         desc: 'Peão captura no centro!',                hint: 'Peão captura em d5' },
  { fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/4P3/2N2N2/PPPP1PPP/R1BQKB1R b KQkq - 0 1', solution: ['f8c5'],   theme: 'Italiana Sólida',      desc: 'Bispo desenvolve!',                      hint: 'Bispo vai para c5' },
  { fen: 'r1b1kb1r/ppppqppp/2n5/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 1', solution: ['c4f7'],  theme: 'Dama em e7',           desc: 'Bispo sacrifica apesar da dama!',        hint: 'Bispo captura em f7' },
  { fen: 'r1bqkbnr/pp1ppppp/2n5/2p5/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1', solution: ['d2d4'],     theme: 'Antissiciliana',       desc: 'Peão ataca no centro!',                  hint: 'Peão vai para d4' },
  { fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R b KQkq - 0 1', solution: ['e5d4'],     theme: 'Abertura do Bispo',    desc: 'Peão captura no centro!',                hint: 'Peão captura em d4' },
  { fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/2P1P3/5N2/PP1P1PPP/RNBQKB1R b KQkq - 0 1', solution: ['e5c4'],  theme: 'Gambito Inglês',       desc: 'Peão aceita o gambito!',                 hint: 'Peão captura em c4' },
  { fen: 'r1bqk2r/pppp1ppp/2n5/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R b kq - 0 1', solution: ['g8f6'],     theme: 'Abertura Italiana',    desc: 'Cavalo desenvolve!',                     hint: 'Cavalo vai para f6' },
  { fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R b kq - 0 1', solution: ['f8c5'],    theme: 'Italiana Clássica',    desc: 'Bispo desenvolve na diagonal!',          hint: 'Bispo vai para c5' },
  { fen: 'rnbqkb1r/pppp1ppp/5n2/4p3/2B1P3/8/PPPP1PPP/RNBQK1NR w KQkq - 0 1', solution: ['c4f7'],     theme: 'Mate do Pastor Var.',  desc: 'Sacrifício surpreendente!',              hint: 'Bispo captura em f7' },
  { fen: 'r1bqkbnr/pp1ppppp/2n5/2p5/3PP3/5N2/PPP2PPP/RNBQKB1R b KQkq - 0 1', solution: ['c5d4'],     theme: 'Gambito de Dama Inv.', desc: 'Peão aceita gambito!',                   hint: 'Peão captura em d4' },
  { fen: 'r1bqkbnr/pp1p1ppp/2n5/2p1p3/3PP3/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: ['d4d5'], theme: 'Siciliana Avanço',     desc: 'Peão avança para conquistar espaço!',   hint: 'Peão vai para d5' },
  { fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/3PP3/2N5/PPP2PPP/R1BQKBNR b KQkq - 0 1', solution: ['e5d4'],     theme: 'Troca Central',        desc: 'Peão captura no centro!',                hint: 'Peão captura em d4' },
  { fen: 'rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 1',    solution: ['d2d4'],       theme: 'Abertura Siciliana',   desc: 'Peão desafia o centro!',                 hint: 'Peão vai para d4' },
  { fen: 'r1bqkbnr/pp1p1ppp/2n5/2p1p1N1/4P3/3P4/PPP2PPP/RNBQKB1R w KQkq - 0 1', solution: ['g5f7'], theme: 'Cavalo Sacrifica',     desc: 'Cavalo entra em f7!',                    hint: 'Cavalo captura em f7' },
  { fen: 'r2qkb1r/ppp1pppp/2np1n2/8/4P3/3P1N2/PPP2PPP/RNBQKB1R w KQkq - 0 1', solution: ['f1e2'],    theme: 'Desenvolvimento',      desc: 'Bispo desenvolve tranquilo!',            hint: 'Bispo vai para e2' },
  { fen: 'r1bqkb1r/pppp1ppp/2n2n2/8/2BpP3/2N2N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['c3d5'],  theme: 'Cavalo d5',            desc: 'Cavalo ataca bispo!',                    hint: 'Cavalo vai para d5' },
  { fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/1PB1P3/5N2/P1PP1PPP/RNBQK2R b KQkq - 0 1', solution: ['c5b4'],  theme: 'Evans Gambito',        desc: 'Bispo captura gambito!',                 hint: 'Bispo captura em b4' },
  { fen: 'r1bqk2r/pppp1ppp/2n2n2/4p3/2BPP3/2N2N2/PPP2PPP/R1BQK2R b kq - 0 1', solution: ['e5d4'],   theme: 'Captura Forçada',      desc: 'Peão captura peão central!',             hint: 'Peão captura em d4' },
  { fen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 0 1',  solution: ['b8c6'],      theme: 'Abertura Clássica',    desc: 'Cavalo desenvolve!',                     hint: 'Cavalo vai para c6' },
  { fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1', solution: ['c4f7'], theme: 'Sacrifício Rápido',    desc: 'Bispo sacrifica em f7!',                 hint: 'Bispo captura em f7' },
  { fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 0 1', solution: ['f8c5'],    theme: 'Italiana Moderna',     desc: 'Bispo desenvolve com pressão!',          hint: 'Bispo vai para c5' },
  { fen: 'r1bqkbnr/ppp2ppp/2np4/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1', solution: ['c4f7'],   theme: 'Italiana Agressiva',   desc: 'Sacrifício surpreendente!',              hint: 'Bispo captura em f7' },

  // --- JULHO ---
  { fen: '6k1/5ppp/8/4P3/8/8/5PPP/6K1 w - - 0 1',                             solution: ['e5e6'],       theme: 'Peão Passado',         desc: 'Peão avança para promoção!',             hint: 'Peão vai para e6' },
  { fen: '8/5kpp/8/4P3/8/8/5KPP/8 w - - 0 1',                                  solution: ['e5e6'],       theme: 'Corrida de Peões',     desc: 'Peão avança mais rápido!',               hint: 'Peão vai para e6' },
  { fen: '8/8/4k3/4p3/4P3/4K3/8/8 w - - 0 1',                                  solution: ['e3d4'],       theme: 'Oposição de Reis',     desc: 'Rei toma oposição!',                     hint: 'Rei vai para d4' },
  { fen: '8/3kp3/8/3P4/8/3K4/8/8 w - - 0 1',                                   solution: ['d3e4'],       theme: 'Final K+P',            desc: 'Rei avança para apoiar peão!',           hint: 'Rei vai para e4' },
  { fen: '4k3/4p3/8/4K3/4P3/8/8/8 w - - 0 1',                                  solution: ['e5d5'],       theme: 'Manobra de Rei',       desc: 'Rei manobra para vencer!',               hint: 'Rei vai para d5' },
  { fen: '8/8/8/4k3/3Pp3/8/8/4K3 b - d3 0 1',                                  solution: ['e4d3'],       theme: 'En passant',           desc: 'Capture en passant!',                    hint: 'Peão captura en passant em d3' },
  { fen: '8/5p2/8/5P2/5K2/8/5k2/8 w - - 0 1',                                  solution: ['f4e4'],       theme: 'Rei e Peão',           desc: 'Rei centraliza para vencer!',            hint: 'Rei vai para e4' },
  { fen: '4k3/8/4K3/8/8/8/4P3/8 w - - 0 1',                                    solution: ['e2e4'],       theme: 'Avanço de Peão',       desc: 'Peão avança dois passos!',               hint: 'Peão vai para e4' },
  { fen: '8/p7/8/8/8/8/P7/8 w - - 0 1',                                        solution: ['a2a4'],       theme: 'Peão Passado',         desc: 'Peão avança para promoção!',             hint: 'Peão vai para a4' },
  { fen: '8/8/8/1k6/8/8/1K6/4R3 w - - 0 1',                                    solution: ['e1b1'],       theme: 'Torre Básica',         desc: 'Torre dá xeque ao rei!',                 hint: 'Torre vai para b1' },
  { fen: '8/8/8/2k5/8/8/2K5/3R4 w - - 0 1',                                    solution: ['d1d5'],       theme: 'Xeque com Torre',      desc: 'Torre dá xeque!',                        hint: 'Torre vai para d5' },
  { fen: '8/8/3k4/8/8/3K4/8/2R5 w - - 0 1',                                    solution: ['c1c6'],       theme: 'Torre Ativa',          desc: 'Torre corta o rei!',                     hint: 'Torre vai para c6' },
  { fen: '8/2k5/8/8/8/2K5/8/1R6 w - - 0 1',                                    solution: ['b1b7'],       theme: 'Torre 7ª Fileira',     desc: 'Torre domina a 7ª!',                     hint: 'Torre vai para b7' },
  { fen: '1r6/2k5/8/8/8/2K5/8/1R6 w - - 0 1',                                  solution: ['b1b8'],       theme: 'Troca de Torres',      desc: 'Torre captura na 8ª!',                   hint: 'Torre vai para b8' },
  { fen: '8/1r6/2k5/8/2K5/8/8/1R6 w - - 0 1',                                  solution: ['b1b7'],       theme: 'Torre Invasora',       desc: 'Torre invade a 7ª!',                     hint: 'Torre vai para b7' },
  { fen: 'r7/1k6/8/8/8/1K6/8/R7 w - - 0 1',                                    solution: ['a1a7'],       theme: 'Torre Corta',          desc: 'Torre corta o rei!',                     hint: 'Torre vai para a7' },
  { fen: '8/8/1k6/8/8/1K6/8/R7 w - - 0 1',                                     solution: ['a1a6'],       theme: 'Escada de Torre',      desc: 'Torre sobe como escada!',                hint: 'Torre vai para a6' },
  { fen: '8/8/8/1k6/8/1K6/8/R7 w - - 0 1',                                     solution: ['a1a5'],       theme: 'Torre e Rei',          desc: 'Torre apoia o rei!',                     hint: 'Torre vai para a5' },
  { fen: '8/8/8/8/1k6/8/1K6/R7 w - - 0 1',                                     solution: ['a1a4'],       theme: 'Xeque Lateral',        desc: 'Torre dá xeque lateral!',                hint: 'Torre vai para a4' },
  { fen: '8/8/8/8/8/1k6/8/RK6 w - - 0 1',                                      solution: ['a1b1'],       theme: 'Mate com Torre',       desc: 'Torre dá mate!',                         hint: 'Torre vai para b1' },
  { fen: '8/6k1/8/8/8/8/6K1/5R2 w - - 0 1',                                    solution: ['f1f7'],       theme: 'Torre Fatal',          desc: 'Torre corta o rei na 7ª!',               hint: 'Torre vai para f7' },
  { fen: '8/5k2/8/8/8/8/5K2/4R3 w - - 0 1',                                    solution: ['e1e7'],       theme: 'Torre Decisiva',       desc: 'Torre vai para a 7ª!',                   hint: 'Torre vai para e7' },
  { fen: '8/4k3/8/8/8/8/4K3/3R4 w - - 0 1',                                    solution: ['d1d7'],       theme: 'Torre Sétima',         desc: 'Torre domina a 7ª fileira!',             hint: 'Torre vai para d7' },
  { fen: '8/3k4/8/8/8/8/3K4/2R5 w - - 0 1',                                    solution: ['c1c7'],       theme: 'Coluna c Livre',       desc: 'Torre vai para 7ª pela coluna c!',       hint: 'Torre vai para c7' },
  { fen: '8/2k5/8/8/8/8/2K5/R7 w - - 0 1',                                     solution: ['a1a7'],       theme: 'Torre a7',             desc: 'Torre conquista a 7ª!',                  hint: 'Torre vai para a7' },
  { fen: '1r6/k7/8/8/8/K7/8/R7 w - - 0 1',                                     solution: ['a1a8'],       theme: 'Captura na 8ª',        desc: 'Torre captura na 8ª!',                   hint: 'Torre captura em a8' },
  { fen: '8/k7/8/8/8/K7/8/R7 w - - 0 1',                                       solution: ['a1a7'],       theme: 'Ataque Torre',         desc: 'Torre ataca rei pelo flanco!',           hint: 'Torre vai para a7' },
  { fen: '8/8/k7/8/8/K7/8/R7 w - - 0 1',                                       solution: ['a1a6'],       theme: 'Xeque de Torre',       desc: 'Torre dá xeque!',                        hint: 'Torre vai para a6' },
  { fen: '8/8/8/k7/8/K7/8/R7 w - - 0 1',                                       solution: ['a1a5'],       theme: 'Torre Ativa',          desc: 'Torre ativa!',                           hint: 'Torre vai para a5' },
  { fen: '8/8/8/8/k7/K7/8/R7 w - - 0 1',                                       solution: ['a1a4'],       theme: 'Xeque com Torre',      desc: 'Torre dá xeque ao rei!',                 hint: 'Torre vai para a4' },
  { fen: '8/8/8/8/8/k7/K7/R7 w - - 0 1',                                       solution: ['a1a3'],       theme: 'Mate em 2',            desc: 'Torre força mate em dois!',              hint: 'Torre vai para a3' },

  // --- AGOSTO ---
  { fen: 'r1bq1rk1/pp2ppbp/2np1np1/8/3NP3/2N1BP2/PPPQ2PP/R3KB1R w KQ - 0 10', solution: ['d4f5'],      theme: 'Cavalo f5',            desc: 'Cavalo salta para f5 dominante!',        hint: 'Cavalo vai para f5' },
  { fen: 'r1bqkb1r/pppp1ppp/2n5/4p1N1/2B1P3/8/PPPP1PPP/RNBQK2R b KQkq - 0 1', solution: ['d8g5'],     theme: 'Ataque ao Cavalo',     desc: 'Dama ataca o cavalo em g5!',             hint: 'Dama vai para g5' },
  { fen: 'r1bqkb1r/pppp1ppp/2n5/8/2BNP3/8/PPP2PPP/RNBQK2R w KQkq - 0 1',     solution: ['d4f5'],       theme: 'Cavalo Agressivo',     desc: 'Cavalo salta para posição forte!',       hint: 'Cavalo vai para f5' },
  { fen: 'r1b1k2r/ppp2ppp/2pb1n2/3pp3/4P3/3P1NP1/PPP1BPBP/R1BQK2R w KQkq - 0 1', solution: ['f3e5'],  theme: 'Cavalo e5',             desc: 'Cavalo captura peão central!',           hint: 'Cavalo vai para e5' },
  { fen: 'r2qkb1r/ppp1pppp/2n2n2/3p4/3P2b1/4PN2/PPP1BPPP/RNBQ1RK1 w kq - 0 1', solution: ['e3d4'],   theme: 'Abertura de Centro',   desc: 'Peão abre o centro!',                    hint: 'Peão captura em d4... vai para d4' },
  { fen: 'r1bqkb1r/pp3ppp/2np1n2/4p3/4P3/2NP1N2/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: ['f3g5'],  theme: 'Pressão em f7',        desc: 'Cavalo pressiona em f7!',                hint: 'Cavalo vai para g5' },
  { fen: 'r1bqkb1r/ppp2ppp/2np1n2/4p3/4P3/3P1NP1/PPP2PBP/RNBQK2R w KQkq - 0 1', solution: ['f3g5'],  theme: 'Ataque ao Flanco',     desc: 'Cavalo ataca ponto fraco!',              hint: 'Cavalo vai para g5' },
  { fen: 'r1bqkb1r/ppp2ppp/2np1n2/4p3/4PP2/3P1N2/PPP3PP/RNBQKB1R w KQkq - 0 1', solution: ['f4f5'],  theme: 'Avanço f5',            desc: 'Peão avança agressivamente!',            hint: 'Peão vai para f5' },
  { fen: '1rbqkb1r/p1pp1ppp/2np1n2/1p2p3/4P3/2NP1N2/PPP1BPPP/R1BQK2R w KQkq - 0 1', solution: ['f3d4'], theme: 'Cavalo Central',     desc: 'Cavalo ocupa centro!',                   hint: 'Cavalo vai para d4' },
  { fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/1PB1P3/5N2/P1PP1PPP/RNBQK2R b KQkq - 0 1', solution: ['c5b4'], theme: 'Evans Gambito',        desc: 'Bispo captura gambito audaz!',           hint: 'Bispo captura em b4' },
  { fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1', solution: ['d2d4'],     theme: 'Abertura Italiana',    desc: 'Peão expande o centro!',                 hint: 'Peão vai para d4' },
  { fen: 'r1bq1rk1/pppp1ppp/2n2n2/4p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R b - - 0 1', solution: ['f8e7'],    theme: 'Desenvolvimento',      desc: 'Bispo desenvolve!',                      hint: 'Bispo vai para e7' },
  { fen: 'r2qk2r/ppp1bppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['c4d5'], theme: 'Bispo Ativo',          desc: 'Bispo toma ponto forte!',                hint: 'Bispo vai para d5' },
  { fen: 'r1bqk1r1/pppp1ppp/2n2n2/4p3/2BPP3/5N2/PPP2PPP/RNBQK2R b KQkq - 0 1', solution: ['e5d4'],    theme: 'Captura Central',      desc: 'Peão captura no centro!',                hint: 'Peão captura em d4' },
  { fen: '4r1k1/ppp2ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/4R1K1 w - - 0 1',    solution: ['c4f7'],       theme: 'Sacrifício Final',     desc: 'Bispo sacrifica decisivamente!',         hint: 'Bispo captura em f7' },
  { fen: '2r3k1/ppp2ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/2R3K1 w - - 0 1',    solution: ['c4f7'],       theme: 'Bispo f7',             desc: 'Sacrifício em f7!',                      hint: 'Bispo captura em f7' },
  { fen: 'r4rk1/ppp2ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/R4RK1 w - - 0 1',    solution: ['c4f7'],       theme: 'Ataque Aberto',        desc: 'Bispo abre o rei!',                      hint: 'Bispo captura em f7' },
  { fen: '5rk1/ppp2ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/5RK1 w - - 0 1',      solution: ['c4f7'],       theme: 'Sacrifício Clássico',  desc: 'Sacrifício clássico italiano!',          hint: 'Bispo captura em f7' },
  { fen: 'r1b2rk1/ppp2ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/R1B2RK1 w - - 0 1', solution: ['c4f7'],     theme: 'Combinação Italiana',  desc: 'Ataque italiano clássico!',              hint: 'Bispo captura em f7' },
  { fen: 'r3r1k1/ppp2ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/R3R1K1 w - - 0 1',  solution: ['c4f7'],       theme: 'Bispo Decisivo',       desc: 'Sacrifício decisivo!',                   hint: 'Bispo captura em f7' },
  { fen: 'r1bqr1k1/ppp2ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/R1BQR1K1 w - - 0 1', solution: ['c4f7'],   theme: 'Sacrifício Aberto',    desc: 'Bispo abre a posição!',                  hint: 'Bispo captura em f7' },
  { fen: '2r2rk1/ppp2ppp/2nb1n2/3pp3/2B1P3/2NP1N2/PPP2PPP/2R2RK1 w - - 0 1', solution: ['c4d5'],       theme: 'Bispo d5',             desc: 'Bispo domina o centro!',                 hint: 'Bispo vai para d5' },
  { fen: 'r4rk1/ppp2ppp/2nb1n2/3pp3/2B1P3/2NP1N2/PPP2PPP/R4RK1 w - - 0 1',   solution: ['c4d5'],       theme: 'Pressão Central',      desc: 'Bispo pressiona o centro!',              hint: 'Bispo vai para d5' },
  { fen: 'r1b2rk1/ppp2ppp/2nb1n2/3pp3/2B1P3/2NP1N2/PPP2PPP/R1B2RK1 w - - 0 1', solution: ['c4d5'],    theme: 'Bispo Central',        desc: 'Bispo toma ponto d5!',                   hint: 'Bispo vai para d5' },
  { fen: 'r3r1k1/ppp2ppp/2nb1n2/3pp3/2B1P3/2NP1N2/PPP2PPP/R3R1K1 w - - 0 1', solution: ['c4d5'],       theme: 'Bispo Ativo',          desc: 'Bispo conquista d5!',                    hint: 'Bispo vai para d5' },
  { fen: '4r1k1/ppp2ppp/2nb1n2/3pp3/2B1P3/2NP1N2/PPP2PPP/4R1K1 w - - 0 1',   solution: ['c4d5'],       theme: 'Centro Forte',         desc: 'Bispo toma centro!',                     hint: 'Bispo vai para d5' },
  { fen: '2r3k1/ppp2ppp/2nb1n2/3pp3/2B1P3/2NP1N2/PPP2PPP/2R3K1 w - - 0 1',   solution: ['c4d5'],       theme: 'Domínio Central',      desc: 'Bispo domina o centro!',                 hint: 'Bispo vai para d5' },
  { fen: '5rk1/ppp2ppp/2nb1n2/3pp3/2B1P3/2NP1N2/PPP2PPP/5RK1 w - - 0 1',     solution: ['c4d5'],       theme: 'Bispo Forte',          desc: 'Bispo ocupa posto avançado!',            hint: 'Bispo vai para d5' },
  { fen: 'r5k1/ppp2ppp/2nb1n2/3pp3/2B1P3/2NP1N2/PPP2PPP/R5K1 w - - 0 1',     solution: ['c4d5'],       theme: 'Bispo e Cavalo',       desc: 'Bispo coopera com cavalos!',             hint: 'Bispo vai para d5' },
  { fen: 'r1b3k1/ppp2ppp/2nb1n2/3pp3/2B1P3/2NP1N2/PPP2PPP/R1B3K1 w - - 0 1', solution: ['c4d5'],       theme: 'Dois Bispos Fortes',   desc: 'Bispo toma ponto central!',              hint: 'Bispo vai para d5' },
  { fen: '1rb3k1/ppp2ppp/2nb1n2/3pp3/2B1P3/2NP1N2/PPP2PPP/1RB3K1 w - - 0 1', solution: ['c4d5'],       theme: 'Bispo Avançado',       desc: 'Bispo avança para posição forte!',       hint: 'Bispo vai para d5' },

  // --- SETEMBRO ---
  { fen: '6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',                              solution: ['e1e8'],       theme: 'Mate em 1',            desc: 'Torre dá mate!',                         hint: 'Torre vai para e8' },
  { fen: '1k1r4/pp1b1R2/3p4/2pPp3/2P1P3/2K5/PP4B1/8 w - - 0 1',               solution: ['d5c6'],       theme: 'Peão Passado',         desc: 'Peão passado decide!',                   hint: 'Peão avança para c6' },
  { fen: 'r1bk3r/p2pBpNp/n4n2/1p1NP2P/6P1/3P4/PPP1K1P1/q1B2R2 w - - 1 0',    solution: ['f1f8'],       theme: 'Sacrifício de Torre',  desc: 'Sacrifique a torre para vencer!',        hint: 'Torre vai para f8' },
  { fen: 'r1bq1rk1/pp2ppbp/2np1np1/8/3NP3/2N1BP2/PPP3PP/R2QKBR1 w Q - 0 10', solution: ['d4f5'],       theme: 'Salto Decisivo',       desc: 'Cavalo salta para f5!',                  hint: 'Cavalo vai para f5' },
  { fen: '6k1/pp4pp/2p5/4Pb2/4p3/1P2Q3/P5PP/5RK1 w - - 0 1',                  solution: ['e5f6'],       theme: 'Bispo f6',             desc: 'Bispo avança com ataque!',               hint: 'Bispo vai para f6' },
  { fen: '5rk1/p4ppp/1p6/3pq3/3B4/1P3Q2/P4PPP/5RK1 w - - 0 1',               solution: ['d4g7'],       theme: 'Bispo g7',             desc: 'Bispo ataca o rei em g7!',               hint: 'Bispo vai para g7' },
  { fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4', solution: ['d1e2'],   theme: 'Desenvolve Dama',      desc: 'Dama apoia a abertura!',                 hint: 'Dama vai para e2' },
  { fen: 'r1bq1rk1/pp3ppp/2p2n2/3p4/2PP4/4BN2/PP2BPPP/R2Q1RK1 w - - 0 1',   solution: ['c4d5'],       theme: 'Pulo de Peão',         desc: 'Peão captura no centro!',                hint: 'Peão captura em d5' },
  { fen: 'r1b1r1k1/ppp2ppp/2n2n2/3pp3/2B1P3/2NP1N2/PPP2PPP/R1B1R1K1 w - - 0 1', solution: ['f3e5'],   theme: 'Ponto e5',             desc: 'Cavalo conquista e5!',                   hint: 'Cavalo vai para e5' },
  { fen: 'r2q1rk1/ppp1bppp/2np1n2/4p3/2B1PP2/2NP1N2/PPP3PP/R1BQ1RK1 w - - 0 1', solution: ['f4f5'],   theme: 'Avanço f5',            desc: 'Peão avança agressivamente!',            hint: 'Peão vai para f5' },
  { fen: 'r1bq1rk1/ppp2ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/R1BQ1RK1 b - - 0 1', solution: ['d6d5'],   theme: 'Contraataque',         desc: 'Peão contraataca no centro!',            hint: 'Peão vai para d5' },
  { fen: 'r1b1rnk1/ppp2ppp/3p1n2/4p3/2B1PP2/2NP1N2/PPP3PP/R1B2RK1 w - - 0 1', solution: ['f4f5'],     theme: 'Ataque Flanco',        desc: 'Peão avança no flanco!',                 hint: 'Peão vai para f5' },
  { fen: 'r1bq1rk1/pp3ppp/2nbpn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/R2Q1RK1 w - - 0 1', solution: ['c4d5'],  theme: 'Centro Aberto',        desc: 'Bispo toma centro!',                     hint: 'Bispo vai para d5' },
  { fen: 'r1b2rk1/ppq2ppp/2nbpn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/R2Q1RK1 w - - 0 1', solution: ['c4d5'],  theme: 'Bispo Avança',         desc: 'Bispo avança para d5!',                  hint: 'Bispo vai para d5' },
  { fen: 'r2q1rk1/pp3ppp/2nbpn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/R2Q1RK1 w - - 0 1', solution: ['c4d5'],   theme: 'Bispo d5 Forte',       desc: 'Bispo conquista d5!',                    hint: 'Bispo vai para d5' },
  { fen: '2r2rk1/pp3ppp/2nbpn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/2R2RK1 w - - 0 1', solution: ['c4d5'],      theme: 'Posição Forte',        desc: 'Bispo ocupa posto avançado!',            hint: 'Bispo vai para d5' },
  { fen: 'r4rk1/pp3ppp/2nbpn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/R4RK1 w - - 0 1',   solution: ['c4d5'],      theme: 'Bispo Forte',          desc: 'Bispo vai para posto forte!',            hint: 'Bispo vai para d5' },
  { fen: '4rrk1/pp3ppp/2nbpn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/4RRK1 w - - 0 1',   solution: ['c4d5'],      theme: 'Torres e Bispo',       desc: 'Bispo avança apoiado pelas torres!',     hint: 'Bispo vai para d5' },
  { fen: 'r1b2rk1/pp3ppp/2n1pn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/R1B2RK1 w - - 0 1', solution: ['c4d5'],   theme: 'Bispo Decisivo',       desc: 'Bispo toma ponto decisivo!',             hint: 'Bispo vai para d5' },
  { fen: '1rb2rk1/pp3ppp/2n1pn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/1RB2RK1 w - - 0 1', solution: ['c4d5'],   theme: 'Centro Dominado',      desc: 'Bispo domina o centro!',                 hint: 'Bispo vai para d5' },
  { fen: 'r1bqr1k1/pp3ppp/2n1pn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/R1BQR1K1 w - - 0 1', solution: ['c4d5'], theme: 'Combinação Central',   desc: 'Bispo conquista d5!',                    hint: 'Bispo vai para d5' },
  { fen: 'r3r1k1/pp3ppp/2nqpn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/R3R1K1 w - - 0 1', solution: ['c4d5'],      theme: 'Bispo e Dama',         desc: 'Bispo e dama cooperam!',                 hint: 'Bispo vai para d5' },
  { fen: 'r3rqk1/pp3ppp/2n1pn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/R3RQK1 w - - 0 1', solution: ['c4d5'],      theme: 'Coordenação',          desc: 'Peças coordenam!',                       hint: 'Bispo vai para d5' },
  { fen: 'r3r1k1/pp1q1ppp/2n1pn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/R3R1K1 w - - 0 1', solution: ['c4d5'],   theme: 'Bispo Atacante',       desc: 'Bispo ataca com força!',                 hint: 'Bispo vai para d5' },
  { fen: 'r1b1r1k1/pp3ppp/2n1pn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/R1B1R1K1 w - - 0 1', solution: ['c4d5'], theme: 'Bispo Agressor',       desc: 'Bispo toma ponto central!',              hint: 'Bispo vai para d5' },
  { fen: 'r2br1k1/pp3ppp/2n1pn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/R2BR1K1 w - - 0 1', solution: ['c4d5'],   theme: 'Força Central',        desc: 'Bispo força situação central!',          hint: 'Bispo vai para d5' },
  { fen: 'r2b1rk1/pp3ppp/2n1pn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/R2B1RK1 w - - 0 1', solution: ['c4d5'],  theme: 'Bispo Poderoso',       desc: 'Bispo é peça poderosa aqui!',            hint: 'Bispo vai para d5' },
  { fen: 'r1b1rrk1/pp3ppp/2n1pn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/R1B1RRK1 w - - 0 1', solution: ['c4d5'], theme: 'Torres Apoiam',        desc: 'Torres apoiam bispo!',                   hint: 'Bispo vai para d5' },
  { fen: '1rb1r1k1/pp3ppp/2n1pn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/1RB1R1K1 w - - 0 1', solution: ['c4d5'], theme: 'Bispo Campeão',        desc: 'Bispo é o campeão da posição!',          hint: 'Bispo vai para d5' },
  { fen: '2b1r1k1/pp3ppp/2n1pn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/2B1R1K1 w - - 0 1', solution: ['c4d5'],   theme: 'Bispo Vitorioso',      desc: 'Bispo conquista posição vencedora!',     hint: 'Bispo vai para d5' },
  { fen: '3br1k1/pp3ppp/2n1pn2/3pp3/2B1P3/2NP1NB1/PPP2PPP/3BR1K1 w - - 0 1', solution: ['c4d5'],      theme: 'Bispo Triunfante',     desc: 'Bispo triunfa no centro!',               hint: 'Bispo vai para d5' },

  // --- OUTUBRO ---
  { fen: 'r3k2r/pp1b1ppp/2np1n2/q1p1p3/2B1P1b1/2NP1N2/PPP1BPPP/R1BQK2R w KQkq - 0 1', solution: ['c4d5'], theme: 'Bispo d5 Forte',   desc: 'Bispo conquista d5!',                    hint: 'Bispo vai para d5' },
  { fen: 'r3k2r/pp1b1ppp/2n2n2/q1p1p3/4P1b1/2NP1N2/PPP1BPPP/R1BQK2R w KQkq - 0 1', solution: ['f3e5'],   theme: 'Cavalo Central',     desc: 'Cavalo captura em e5!',                  hint: 'Cavalo vai para e5' },
  { fen: 'r3kb1r/pp1b1ppp/2np1n2/q3p3/2B1P1B1/2NP1N2/PPP2PPP/R2QK2R w KQkq - 0 1', solution: ['g4f5'],   theme: 'Bispo f5',           desc: 'Bispo avança para f5!',                  hint: 'Bispo vai para f5' },
  { fen: 'r3kb1r/pp3ppp/2np1n2/q3p1b1/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['f3e5'],    theme: 'Cavalo Ataca',       desc: 'Cavalo captura em e5!',                  hint: 'Cavalo vai para e5' },
  { fen: 'r3kbr1/pp1b1ppp/2np1n2/q3p3/2B1P1B1/2NP1N2/PPP2PPP/R2QK2R w KQkq - 0 1', solution: ['c4d5'],  theme: 'Bispo d5',           desc: 'Bispo domina d5!',                       hint: 'Bispo vai para d5' },
  { fen: 'r3kb2/pp1b1ppr/2np1n2/q3p3/2B1P1B1/2NP1N2/PPP2PPP/R2QK2R w KQ - 0 1', solution: ['c4d5'],      theme: 'Bispo Forte',        desc: 'Bispo ocupa d5!',                        hint: 'Bispo vai para d5' },
  { fen: 'r4b1r/pp1bkppp/2np1n2/q3p3/2B1P1B1/2NP1N2/PPP2PPP/R2QK2R w KQ - 0 1', solution: ['c4d5'],     theme: 'Posição Forte',      desc: 'Bispo ocupa posto forte!',               hint: 'Bispo vai para d5' },
  { fen: 'r3kb1r/pp3ppp/2npbn2/q3p3/2B1P1B1/2NP1N2/PPP2PPP/R2QK2R w KQkq - 0 1', solution: ['g4f5'],    theme: 'Bispo Agressivo',    desc: 'Bispo ataca em f5!',                     hint: 'Bispo vai para f5' },
  { fen: 'r3kb1r/pp3ppp/2np1n2/q3p1b1/4P1B1/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['g4f5'],   theme: 'Troca de Bispos',    desc: 'Bispo captura bispo adversário!',        hint: 'Bispo vai para f5' },
  { fen: 'r3kb1r/pp3ppp/2np1n2/q3p3/2B1P1b1/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['c4d5'],   theme: 'Bispo Forte d5',     desc: 'Bispo conquista d5!',                    hint: 'Bispo vai para d5' },
  { fen: 'r3k2r/pp3ppp/2npbn2/q3p3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['f3e5'],       theme: 'Cavalo e5',          desc: 'Cavalo captura em e5!',                  hint: 'Cavalo vai para e5' },
  { fen: 'r3k2r/pp3ppp/2np1n2/q3pb2/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['c4d5'],      theme: 'Centro Branco',      desc: 'Bispo domina centro!',                   hint: 'Bispo vai para d5' },
  { fen: 'r3k2r/pp3ppp/2np1n2/q3p3/2B1Pb2/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['f3e5'],      theme: 'Captura Central',    desc: 'Cavalo captura centralmente!',           hint: 'Cavalo vai para e5' },
  { fen: 'r3k2r/pp3ppp/2npbn2/q7/2B1p3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['f3e5'],          theme: 'Cavalo Ativo',       desc: 'Cavalo ativa no centro!',                hint: 'Cavalo vai para e5' },
  { fen: 'r3k2r/pp3ppp/2np1n2/q3p3/2B1P3/2NP1Nb1/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['c4d5'],      theme: 'Bispo Salva',        desc: 'Bispo move antes de ser capturado!',     hint: 'Bispo vai para d5' },
  { fen: 'r3k2r/pp3ppp/2np1n2/q3p1b1/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['c4f7'],     theme: 'Sacrifício f7',      desc: 'Bispo sacrifica em f7!',                 hint: 'Bispo captura em f7' },
  { fen: 'r3k2r/pp3ppp/2np1n2/q2bp3/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['c4d5'],      theme: 'Bispo Captura',      desc: 'Bispo captura bispo adversário!',        hint: 'Bispo captura em d5' },
  { fen: 'r3k2r/pp3ppp/2npbn2/q3p3/4P3/2NP1N2/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: ['f1b5'],        theme: 'Bispo b5',           desc: 'Bispo prende o cavalo!',                 hint: 'Bispo vai para b5' },
  { fen: 'r3k2r/pp3ppp/2np1n2/qb2p3/4P3/2NP1N2/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: ['f1d3'],       theme: 'Bispo d3',           desc: 'Bispo desenvolve em d3!',                hint: 'Bispo vai para d3' },
  { fen: 'r3k2r/pp3ppp/2np1n2/q3p3/4P3/2NP1N2/PPP2PPP/R1BQKB1R w KQkq - 0 1', solution: ['f1e2'],         theme: 'Bispo e2',           desc: 'Bispo desenvolve tranquilo!',            hint: 'Bispo vai para e2' },
  { fen: 'r2qk2r/pp3ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/R2QK2R w KQkq - 0 1', solution: ['c4d5'],         theme: 'Bispo Forte',        desc: 'Bispo avança para posto forte!',         hint: 'Bispo vai para d5' },
  { fen: 'r2qkb1r/pp3ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/R2QK2R w KQkq - 0 1', solution: ['c4d5'],        theme: 'Bispo d5',           desc: 'Bispo toma ponto central!',              hint: 'Bispo vai para d5' },
  { fen: 'r2q1rk1/pp3ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/R2Q1RK1 w - - 0 1', solution: ['c4d5'],           theme: 'Bispo Central',      desc: 'Bispo domina o centro!',                 hint: 'Bispo vai para d5' },
  { fen: 'r2q1r1k/pp3ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/R2Q1R1K w - - 0 1', solution: ['c4d5'],           theme: 'Bispo Forte',        desc: 'Bispo conquista d5!',                    hint: 'Bispo vai para d5' },
  { fen: '2rq1rk1/pp3ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/2RQ1RK1 w - - 0 1', solution: ['c4d5'],           theme: 'Bispo e Torres',     desc: 'Bispo apoiado pelas torres!',            hint: 'Bispo vai para d5' },
  { fen: '3q1rk1/pp3ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/3Q1RK1 w - - 0 1',   solution: ['c4d5'],            theme: 'Bispo Decisivo',     desc: 'Bispo decide a posição!',                hint: 'Bispo vai para d5' },
  { fen: '3q1r1k/pp3ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/3Q1R1K w - - 0 1',   solution: ['c4d5'],            theme: 'Bispo Vence',        desc: 'Bispo leva à vitória!',                  hint: 'Bispo vai para d5' },
  { fen: '4qrk1/pp3ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/4QRK1 w - - 0 1',     solution: ['c4d5'],            theme: 'Bispo Forte',        desc: 'Bispo ocupa posto forte!',               hint: 'Bispo vai para d5' },
  { fen: '4qr1k/pp3ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/4QR1K w - - 0 1',     solution: ['c4d5'],            theme: 'Bispo Ativo',        desc: 'Bispo ativa na posição!',                hint: 'Bispo vai para d5' },
  { fen: '5rqk/pp3ppp/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/5RQK w - - 0 1',       solution: ['c4d5'],            theme: 'Bispo Campeão',      desc: 'Bispo é o campeão!',                     hint: 'Bispo vai para d5' },
  { fen: '5r1k/pp3ppq/2np1n2/4p3/2B1P3/2NP1N2/PPP2PPP/5R1K w - - 0 1',       solution: ['c4d5'],            theme: 'Bispo Final',        desc: 'Bispo decide o final!',                  hint: 'Bispo vai para d5' },

  // --- NOVEMBRO ---
  { fen: '8/8/8/3Q4/8/3k4/8/3K4 w - - 0 1',                                    solution: ['d5d3'],       theme: 'Mate com Dama',        desc: 'Dama força mate!',                       hint: 'Dama vai para d3' },
  { fen: '8/8/8/8/3Q4/3k4/8/3K4 w - - 0 1',                                    solution: ['d4d3'],       theme: 'Dama Mata',            desc: 'Dama dá mate!',                          hint: 'Dama vai para d3' },
  { fen: '3k4/8/3K4/3Q4/8/8/8/8 w - - 0 1',                                    solution: ['d5d8'],       theme: 'Dama e Rei',           desc: 'Dama dá xeque-mate!',                    hint: 'Dama vai para d8' },
  { fen: '8/8/3k4/8/3K4/8/8/3Q4 w - - 0 1',                                    solution: ['d1d6'],       theme: 'Dama Forte',           desc: 'Dama avança!',                           hint: 'Dama vai para d6' },
  { fen: '8/3k4/8/8/3Q4/8/3K4/8 w - - 0 1',                                    solution: ['d4d7'],       theme: 'Dama Ataca',           desc: 'Dama ataca o rei!',                      hint: 'Dama vai para d7' },
  { fen: '3k4/8/8/8/3K4/8/8/3Q4 w - - 0 1',                                    solution: ['d1d8'],       theme: 'Dama Rápida',          desc: 'Dama dá xeque-mate!',                    hint: 'Dama vai para d8' },
  { fen: '2k5/8/2K5/2Q5/8/8/8/8 w - - 0 1',                                    solution: ['c5c8'],       theme: 'Dama Mata Canto',      desc: 'Dama dá mate no canto!',                 hint: 'Dama vai para c8' },
  { fen: '8/2k5/8/2K5/2Q5/8/8/8 w - - 0 1',                                    solution: ['c4c7'],       theme: 'Dama c7+',             desc: 'Dama dá xeque!',                         hint: 'Dama vai para c7' },
  { fen: 'k7/8/K7/8/Q7/8/8/8 w - - 0 1',                                       solution: ['a4a8'],       theme: 'Dama a8',              desc: 'Dama dá mate!',                          hint: 'Dama vai para a8' },
  { fen: '8/k7/K7/8/Q7/8/8/8 w - - 0 1',                                       solution: ['a4a7'],       theme: 'Dama a7+',             desc: 'Dama dá xeque!',                         hint: 'Dama vai para a7' },
  { fen: '8/8/k7/K7/Q7/8/8/8 w - - 0 1',                                       solution: ['a4a6'],       theme: 'Dama Avança',          desc: 'Dama dá xeque ao rei!',                  hint: 'Dama vai para a6' },
  { fen: '8/8/8/k7/K7/Q7/8/8 w - - 0 1',                                       solution: ['a3a5'],       theme: 'Dama Xeque',           desc: 'Dama dá xeque lateral!',                 hint: 'Dama vai para a5' },
  { fen: '8/8/8/8/k7/K7/Q7/8 w - - 0 1',                                       solution: ['a2a4'],       theme: 'Dama Corta',           desc: 'Dama corta o rei!',                      hint: 'Dama vai para a4' },
  { fen: '8/8/8/8/8/k7/K7/Q7 w - - 0 1',                                       solution: ['a1a3'],       theme: 'Dama Mate',            desc: 'Dama força mate!',                       hint: 'Dama vai para a3' },
  { fen: '8/6k1/8/8/8/8/6K1/5Q2 w - - 0 1',                                    solution: ['f1f7'],       theme: 'Dama f7',              desc: 'Dama corta o rei!',                      hint: 'Dama vai para f7' },
  { fen: '8/5k2/8/8/8/8/5K2/4Q3 w - - 0 1',                                    solution: ['e1e7'],       theme: 'Dama e7',              desc: 'Dama vai para a 7ª!',                    hint: 'Dama vai para e7' },
  { fen: '8/4k3/8/8/8/8/4K3/3Q4 w - - 0 1',                                    solution: ['d1d7'],       theme: 'Dama d7',              desc: 'Dama ataca rei!',                        hint: 'Dama vai para d7' },
  { fen: '8/3k4/8/8/8/8/3K4/2Q5 w - - 0 1',                                    solution: ['c1c7'],       theme: 'Dama c7',              desc: 'Dama invade c7!',                        hint: 'Dama vai para c7' },
  { fen: '8/2k5/8/8/8/8/2K5/1Q6 w - - 0 1',                                    solution: ['b1b7'],       theme: 'Dama b7',              desc: 'Dama vai para b7!',                      hint: 'Dama vai para b7' },
  { fen: '8/1k6/8/8/8/8/1K6/Q7 w - - 0 1',                                     solution: ['a1a7'],       theme: 'Dama a7',              desc: 'Dama corta o rei!',                      hint: 'Dama vai para a7' },
  { fen: '1k6/8/1K6/8/Q7/8/8/8 w - - 0 1',                                     solution: ['a4b4'],       theme: 'Dama b4',              desc: 'Dama aperta o rei!',                     hint: 'Dama vai para b4' },
  { fen: '2k5/8/2K5/8/Q7/8/8/8 w - - 0 1',                                     solution: ['a4c4'],       theme: 'Dama c4',              desc: 'Dama corta o rei pela coluna!',          hint: 'Dama vai para c4' },
  { fen: '3k4/8/3K4/8/Q7/8/8/8 w - - 0 1',                                     solution: ['a4d4'],       theme: 'Dama d4',              desc: 'Dama corta o rei!',                      hint: 'Dama vai para d4' },
  { fen: '4k3/8/4K3/8/Q7/8/8/8 w - - 0 1',                                     solution: ['a4e4'],       theme: 'Dama e4',              desc: 'Dama corta o rei pela fileira!',         hint: 'Dama vai para e4' },
  { fen: '5k2/8/5K2/8/Q7/8/8/8 w - - 0 1',                                     solution: ['a4f4'],       theme: 'Dama f4',              desc: 'Dama corta o rei!',                      hint: 'Dama vai para f4' },
  { fen: '6k1/8/6K1/8/Q7/8/8/8 w - - 0 1',                                     solution: ['a4g4'],       theme: 'Dama g4',              desc: 'Dama avança lateralmente!',              hint: 'Dama vai para g4' },
  { fen: '7k/8/7K/8/Q7/8/8/8 w - - 0 1',                                       solution: ['a4h4'],       theme: 'Dama h4',              desc: 'Dama corta o rei no canto!',             hint: 'Dama vai para h4' },
  { fen: '8/7k/8/7K/Q7/8/8/8 w - - 0 1',                                       solution: ['a4h5'],       theme: 'Dama h5+',             desc: 'Dama dá xeque!',                         hint: 'Dama vai para h5' },
  { fen: '8/8/7k/8/Q6K/8/8/8 w - - 0 1',                                       solution: ['a4h4'],       theme: 'Dama Força Mate',      desc: 'Dama força mate!',                       hint: 'Dama vai para h4' },
  { fen: '8/8/8/7k/Q6K/8/8/8 w - - 0 1',                                       solution: ['a4h4'],       theme: 'Dama Fatal',           desc: 'Dama é fatal!',                          hint: 'Dama vai para h4' },
  { fen: '8/8/8/8/Q5kK/8/8/8 w - - 0 1',                                       solution: ['a4g4'],       theme: 'Mate de Dama',         desc: 'Dama dá mate!',                          hint: 'Dama vai para g4' },

  // --- DEZEMBRO ---
  { fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4', solution: ['d1e2'],   theme: 'Italiano Moderno',     desc: 'Dama desenvolve!',                       hint: 'Dama vai para e2' },
  { fen: 'r1bqkb1r/pppp1Npp/2n5/4p3/2B1P3/8/PPPP1PPP/RNBQKB1R b KQkq - 0 1', solution: ['d8f6'],      theme: 'Defesa ao Cavalo',     desc: 'Dama deve recapturar!',                  hint: 'Dama captura em f7' },
  { fen: '6k1/5ppp/8/8/8/5N2/5PPP/6K1 w - - 0 1',                              solution: ['f3e5'],       theme: 'Cavalo Ativo',         desc: 'Cavalo ocupa posto central!',            hint: 'Cavalo vai para e5' },
  { fen: '6k1/5ppp/8/4N3/8/8/5PPP/6K1 w - - 0 1',                              solution: ['e5f7'],       theme: 'Cavalo f7',            desc: 'Cavalo ataca em f7!',                    hint: 'Cavalo vai para f7' },
  { fen: '5k2/5ppp/8/4N3/8/8/5PPP/5K2 w - - 0 1',                              solution: ['e5f7'],       theme: 'Garfo de Cavalo',      desc: 'Cavalo faz garfo!',                      hint: 'Cavalo vai para f7' },
  { fen: 'r1bqkb1r/pppp1ppp/8/4p3/2BnP3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1', solution: ['c4f7'],         theme: 'Sacrifício c4-f7',     desc: 'Bispo sacrifica em f7!',                 hint: 'Bispo captura em f7' },
  { fen: 'r2qkb1r/ppp1pppp/2n5/3pN3/4P3/8/PPP2PPP/RNBQKB1R w KQkq - 0 1',   solution: ['e5f7'],         theme: 'Cavalo f7 Decisivo',   desc: 'Cavalo destrói posição negra!',          hint: 'Cavalo captura em f7' },
  { fen: 'r1bq1rk1/pp3ppp/2np4/4p3/2B1Pn2/2NP1N2/PPP2PPP/R1BQ1RK1 w - - 0 1', solution: ['c4f7'],      theme: 'Sacrifício Duplo',     desc: 'Bispo sacrifica!',                       hint: 'Bispo captura em f7' },
  { fen: 'r1bqk2r/pppp1ppp/2n5/2b1p1N1/4P3/8/PPPP1PPP/RNBQKB1R w KQkq - 0 1', solution: ['g5f7'],     theme: 'Cavalo Sacrifica',     desc: 'Cavalo sacrifica em f7!',                hint: 'Cavalo captura em f7' },
  { fen: 'r1bq1rk1/pp3ppp/2np4/4p3/2B1P3/2NP1N2/PPP2PPP/R1BQ1RK1 w - - 0 1', solution: ['c4f7'],      theme: 'Bispo Ataca',          desc: 'Bispo sacrifica em f7!',                 hint: 'Bispo captura em f7' },
  { fen: 'r2qkb1r/ppp1pppp/2n2n2/3p4/2B1P1b1/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['c4f7'], theme: 'Ataque em f7',         desc: 'Bispo ataca f7!',                        hint: 'Bispo captura em f7' },
  { fen: 'r2qkb1r/pp1npppp/2p2n2/3p4/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['c4d5'],  theme: 'Bispo Ativo',          desc: 'Bispo toma centro!',                     hint: 'Bispo vai para d5' },
  { fen: 'r2qkb1r/pp2pppp/2np1n2/2p5/2B1P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 0 1', solution: ['c4d5'],  theme: 'Bispo d5',             desc: 'Bispo domina o centro!',                 hint: 'Bispo vai para d5' },
  { fen: 'r1bq1rk1/pp2ppbp/2np1np1/8/4P3/2NP1N2/PPP1BPPP/R1BQ1RK1 w - - 0 1', solution: ['f3g5'],      theme: 'Cavalo g5',            desc: 'Cavalo ataca f7!',                       hint: 'Cavalo vai para g5' },
  { fen: 'r1bq1rk1/pp2ppbp/2np1np1/8/4P1P1/2NP1N2/PPP1BP1P/R1BQ1RK1 w - - 0 1', solution: ['g4g5'],   theme: 'Avanço g5',            desc: 'Peão avança agressivamente!',            hint: 'Peão vai para g5' },
  { fen: 'r1bq1rk1/pp2pp1p/2np1np1/6p1/4P3/2NP1N2/PPP1BPPP/R1BQ1RK1 w - - 0 1', solution: ['h2h4'],   theme: 'Avanço h4',            desc: 'Peão h4 ataca a estrutura!',             hint: 'Peão vai para h4' },
  { fen: 'r1bqr1k1/pp2pp1p/2np1np1/6p1/4P3/2NP1N1P/PPP1BPP1/R1BQ1RK1 w - - 0 1', solution: ['f3g5'],  theme: 'Cavalo Avança',        desc: 'Cavalo salta para g5!',                  hint: 'Cavalo vai para g5' },
  { fen: 'r1bq1rk1/pp2pp2/2np1npp/6N1/4P3/2NP4/PPP1BPPP/R1BQ1RK1 w - - 0 1', solution: ['g5f7'],       theme: 'Cavalo f7',            desc: 'Cavalo sacrifica em f7!',                hint: 'Cavalo captura em f7' },
  { fen: 'r1bq1rk1/pp2p2p/2np1npp/4N3/4PP2/2NP4/PPP1B1PP/R1BQ1RK1 w - - 0 1', solution: ['e5f7'],      theme: 'Sacrifício Cavalo',    desc: 'Cavalo sacrifica em f7!',                hint: 'Cavalo captura em f7' },
  { fen: 'r1bq1r1k/pp2p2p/2np1npp/4N3/4PP2/2NP4/PPP1B1PP/R1BQ1R1K w - - 0 1', solution: ['e5f7'],      theme: 'Cavalo Fatal',         desc: 'Cavalo destrói defesa!',                 hint: 'Cavalo captura em f7' },
  { fen: 'r1bqr2k/pp2p2p/2np1npp/4N3/4PP2/2NP4/PPP1B1PP/R1BQR2K w - - 0 1',  solution: ['e5f7'],       theme: 'Ataque Mate',          desc: 'Cavalo sacrifica para o mate!',          hint: 'Cavalo captura em f7' },
  { fen: '1rbqr2k/pp2p2p/2np1npp/4N3/4PP2/2NP4/PPP1B1PP/1RBQR2K w - - 0 1',  solution: ['e5f7'],       theme: 'Combinação Final',     desc: 'Cavalo destrói a posição negra!',        hint: 'Cavalo captura em f7' },
  { fen: '1rbq3k/pp2pr1p/2np1npp/4N3/4PP2/2NP4/PPP1B1PP/1RBQ3K w - - 0 1',   solution: ['e5f7'],       theme: 'Cavalo Vence',         desc: 'Cavalo vence decisivamente!',            hint: 'Cavalo captura em f7' },
  { fen: '1rbq2rk/pp2p2p/2np1npp/4N3/4PP2/2NP4/PPP1B1PP/1RBQ2RK w - - 0 1',  solution: ['e5f7'],       theme: 'Mate Forçado',         desc: 'Cavalo força mate!',                     hint: 'Cavalo captura em f7' },
  { fen: '1r1q1brk/pp2p2p/2np1npp/4N3/4PP2/2NP4/PPP1B1PP/1R1Q1BRK w - - 0 1', solution: ['e5f7'],      theme: 'Combinação Mate',      desc: 'Combinação leva ao mate!',               hint: 'Cavalo captura em f7' },
  { fen: '2rq1brk/pp2p2p/2np1npp/4N3/4PP2/2NP4/PPP1B1PP/2RQ1BRK w - - 0 1',  solution: ['e5f7'],       theme: 'Cavalo Poderoso',      desc: 'Cavalo é peça poderosa!',                hint: 'Cavalo captura em f7' },
  { fen: '2rq1b1k/pp2pr1p/2np1npp/4N3/4PP2/2NP4/PPP1B1PP/2RQ1B1K w - - 0 1', solution: ['e5f7'],       theme: 'Cavalo Decisivo',      desc: 'Cavalo decide o jogo!',                  hint: 'Cavalo captura em f7' },
  { fen: '3q1b1k/pp2prrp/2np1npp/4N3/4PP2/2NP4/PPP1B1PP/3Q1B1K w - - 0 1',   solution: ['e5f7'],       theme: 'Lance Vencedor',       desc: 'Lance que vence a partida!',             hint: 'Cavalo captura em f7' },
  { fen: '4qb1k/pp2pr1p/2np1npp/4N3/4PP2/2NP4/PPP1B1PP/4QB1K w - - 0 1',     solution: ['e5f7'],       theme: 'Ataque Decisivo',      desc: 'Ataque decide a partida!',               hint: 'Cavalo captura em f7' },
  { fen: '5b1k/pp2qr1p/2np1npp/4N3/4PP2/2NP4/PPP1B1PP/5B1K w - - 0 1',       solution: ['e5f7'],       theme: 'Cavalo Final',         desc: 'Cavalo encerra a partida!',              hint: 'Cavalo captura em f7' },
  { fen: '6bk/pp2qr1p/2np1npp/4N3/4PP2/2NP4/PPP1B1PP/6BK w - - 0 1',         solution: ['e5f7'],       theme: 'Xeque-Mate do Cavalo', desc: 'Cavalo dá xeque-mate!',                  hint: 'Cavalo captura em f7' },
  { fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4', solution: ['c4f7'],   theme: 'Natal do Xadrez',      desc: 'Feliz Natal com sacrifício!',            hint: 'Bispo captura em f7 - Feliz Natal! 🎄' }
];
